stages:
    - demo
    - deploy

demo-site:
    stage: demo
    timeout: 25m
    allow_failure: true
    tags:
        - demo
    before_script:
        - python3 -m pip install --user virtualenv
        - python3 -m virtualenv venv
        - source venv/bin/activate
        - python3 -m pip install -r requirements.txt
    script:
        - timeout 1m python3 issmap.py; test $? -eq 124 && echo Timeout
    only:
        - /^feature\/.*$/
        - development

deploy:
    stage: deploy
    timeout: 25m
    allow_failure: false
    tags:
        - deploy
    script:
        - ansible-playbook ./deploy.yaml
          -i inventory.yaml
          --extra-vars "ansible_become_pass=$ISSMAP_ROOT_PASS"
          --vault-password-file vault-password-file.sh
    only:
        - development
